// <auto-generated />
using System;
using GetData.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetData.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221024203856_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GetData.Domain.Entities.DataInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DataInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LocalIpv4")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MacAddr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PublicIpv4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataInfoId");

                    b.ToTable("DataInfo");
                });

            modelBuilder.Entity("GetData.Domain.Entities.DataInfo", b =>
                {
                    b.HasOne("GetData.Domain.Entities.DataInfo", null)
                        .WithMany("DataInfos")
                        .HasForeignKey("DataInfoId");
                });

            modelBuilder.Entity("GetData.Domain.Entities.DataInfo", b =>
                {
                    b.Navigation("DataInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
